### ISSUE TITLE
Installing kubler.sh

### ISSUE THREAD

**Issue by jbergstroem** [edannenberg/kubler#107]
See this issue as a discussion for how we should encourage users to "install" kubler. As is, I see two approaches:

1. (current): pull/get the kubler.sh tarball and use in-place
2. Create a `install.sh` that installs `kubler` into $bindir, templates into $sharedir/kubler

The second path is imo a honorable goal but introducing the following issues:

1. file access rights and multi-user: I suggest we just avoid this by making the assumption that user is $superuser -- similar to how they would access docker.
2. where to store distfiles/rootfs.tar/etc: I suggest we create a structure in $tmp (not /tmp, but /private/... for mac and something similar for unix/linux such as /var/lib/tmp)
3. ?

**Comment by edannenberg** [comment]
Personally I favour the simple solution, `git clone` to a user land dir like `~/tools/kubler`, add the provided `bin` dir with the symlink to your PATH and just occasionally run git pull to update, we could also take care of this with the `update` command. Uninstalling is then just a matter of removing the kubler dir and PATH entry.

What do we gain by installing like a system app? 

> 2. where to store distfiles/rootfs.tar/etc: I suggest we create a structure in $tmp (not /tmp, but /private/... for mac and something similar for unix/linux such as /var/lib/tmp)

Moving `rootfs.tar` into a tmp directory is probably a good thing either way, but that still leaves the `PACKAGES.md` file, which should remain inside the image dir.

**Comment by UralZima** [comment]
If it will be in PATH, I think '.sh' is not needed. No any app use it, when it is available globally.
I see it in such way:
Makefile. 
make install: Copying kubler.sh to /usr/bin/kubler, kubler.conf to /etc/kubler.conf
Rest goes to /usr/lib/kubler. 
make uninstall: remove all this.
make update? git pull and update

I don't like idea of ~/tools/kubler. Being a bash script, this project does big work and doesn't matter which language used. I want to 'make install' and forget about it, and use like
root# kubler --help

**Comment by jbergstroem** [comment]
Expanding on my thoughts:

1. `kubler.sh` -> `$prefix/sbin/kubler`
2. `kubler.conf` -> `$prefix/etc/kubler.conf` (suggesting we silently source ~/.kubler.conf and `KUBLER_CONF=path/to/conf` following main config, overrides in that order)
3. builder configs and templates -> `$prefix/share/kubler/...`

Having the config flexibility will make it easy for you to add "local" (`~`) templates.

**Comment by UralZima** [comment]
Sounds good

**Comment by edannenberg** [comment]
Again, personally I think of Kubler as a user land tool, so I don't see much value in installing it as a system tool. That being said I'll probably accept a PR for this. :yum:

>@UralZima said:
I don't like idea of ~/tools/kubler. Being a bash script, this project does big work and doesn't matter which language used. I want to 'make install' and forget about it, and use like root# kubler --help

You can already run `sudo ln -s /path/to/kubler.sh /usr/local/bin/kubler` and have the desired functionality. The `bin/` directory that comes with kubler also has a symlink so you can alternately just add `export PATH="${PATH}:/path/to/kubler/bindir"` to your `.bashrc`.

**Comment by edannenberg** [comment]
> @jbergstroem said:
Having the config flexibility will make it easy for you to add "local" (~) templates. This is where your packages.md/etc will be stored as well. I even think we should encourage these to be checked into a git repo.

I can see a `~/.kubler` dir being useful in general, could also be used to add custom command/engine scripts. `PACKAGES.md` should however always stay inside the image dir IMO, the only exception being the kubler namespace when building from outside the kubler dir.

**Comment by jbergstroem** [comment]
@edannenberg I agree that `PACKAGES.md` always should live in image dir -- I guess what I'm also saying is that images provided by upstream should perhaps be seen as read only with the added notion of 'fork and change!'.

**Comment by edannenberg** [comment]
As I'm about to finish Bash completion support for Kubler I'd like to revisit this.

To work around the mentioned issues regarding Kubler's own namespace when installed as a system app it should be cleaner to change the fundamental build behaviour a bit instead of trying to work around system/user issues with the current way.

* i'd like to keep the current way of just cloning the repo and hacking away, but installing as system app should also be supported
* when installed as system app the `local` namespace type will no longer be available, only userland namespace dirs
* instead create a complete copy of the `kubler` namespace dir at `~/.kubler/somedir` as part of creating a new namespace via `kubler new`, this should avoid all multiuser/permission issues and make the `kubler` namespace reusable for any namespace dirs a user might have
* keeping the `kubler` namespace updated will require some more thought, probably time to move the `kubler` images into a separate repo

**Comment by r7l** [comment]
As someone relatively new to Docker on Gentoo, i've found Kubler only by coincidence and think this needs to be mentioned at least in Gentoo Wiki Docker page. This page currently only holds a section about a Crossdev setup for your software you want to use in Docker but Kubler is the much better choice.

I can only support the request to move Kubler to /usr/bin, /usr/lib with proper /etc configuration instead of having it in some directory under /home. I am one of those using proper ebuilds for everything over custom git pull commands. I know it's my first comment around here but a release with an ebuild should be the way to go, given this based on Gentoo anyways.

Thanks allot for all the hard work you've put into this.

**Comment by r7l** [comment]
I've added a reference to Kubler to the Gentoo Wiki Docker page.

**Comment by edannenberg** [comment]
Hi, I finished most of the work for this over the holidays, it's gonna be part of a bigger update though, hopefully out by the end of this week.

**Comment by edannenberg** [comment]
0.9.0 ebuild will be up soon.
