### ISSUE TITLE
build should fail if build.sh has a bad syntax

### ISSUE THREAD

**Issue by azimut** [edannenberg/kubler#124]
I found this having a bug on the **finish_rootfs_build** the script was sourced with the error but this hook never ran because it had an error. I think the whole build should fail if build.sh doesn't pass a "bash -n build.sh" test or source returns an error

**Comment by edannenberg** [comment]
This is currently somewhat [intentional](https://github.com/edannenberg/kubler/blob/master/lib/bob-core/build-root.sh#L443). IIRC there was a weird issue when sourcing `build.sh` failing the build for no (apparent) reason. This was way back though, gonna take a closer look at this again so thanks for bringing it up.

**Comment by edannenberg** [comment]
Build fails now on syntax errors in a image's `build.sh`.
