### ISSUE TITLE
kubler/bash fails to build with the recently stabilized sys-libs/ncurses-6.1_p20181020

### ISSUE THREAD

**Issue by tifv** [edannenberg/kubler#163]
sys-libs/ncurses fails configure stage, see [build.log](https://github.com/edannenberg/kubler/files/3410307/build.log). (Also maybe [config.log](https://github.com/edannenberg/kubler/files/3410308/cross-config.log) helps.)
```
checking whether the C compiler works...  * /var/tmp/portage/sys-apps/sandbox-2.13/work/sandbox-2.13/libsandbox/trace.c:_do_ptrace():75: failure (Operation not permitted):
 * ISE:_do_ptrace: ptrace(PTRACE_TRACEME, ..., 0x0000000000000000, 0x0000000000000000): Operation not permitted
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
```

Currently keyworded next version (sys-libs/ncurses-6.1_p20190609) fails with the same problem when merged in kubler interactive mode. Previous version (sys-libs/ncurses-6.1-r2) merges without problems.

(Kubler version 0.9.2.)

…or should it be reported as a Gentoo bug? I am not sure what exactly is causing the problem.

**Comment by edannenberg** [comment]
Hi, thanks for reporting. Root cause:

     * ISE:_do_ptrace: ptrace(PTRACE_TRACEME, ..., 0x0000000000000000, 0x0000000000000000): Operation not permitted

Looks like the latest ncurses ebuild is using Portage's sandbox feature which requires `ptrace` permissions to run, per default this is disabled for Docker containers. Fix is [up](https://github.com/edannenberg/kubler-images/commit/d579bc36e64f5ac4629d01d0d7f532ef073b287f), please run `kubler update` and build as usual.

**Comment by edannenberg** [comment]
Assuming this is resolved, feel free to reopen if this is still an issue for you.
