### ISSUE TITLE
RFE: extending kubler-build-root to pass options to emerge

### ISSUE THREAD

**Issue by TerraTech** [edannenberg/kubler#192]
Before I submit a patch, would you be open to the following workflow?

_Current flow_:
```
$ kubler build foo/bar -Fi
kubler-bob / # configure_rootfs_build
kubler-bob / # BOB_EMERGE_OPT='--color=y -tpv' kubler-build-root | less
```
_New flow_:
```
$ kubler build foo/bar -Fi
kubler-bob / # kubler-build-root -tpv | less
```

Before continuing, is there another script/function, that I overlooked, that can be called to run ```emerge``` in the ```/emerge-root/``` rootfs context?

Both ```configure_rootfs_build``` and ```--color=y``` will be executed in ```kubler-build-root```.  The ```--color=y``` option is needed in case you are piping the output.  If there are options passed to ```kubler-build-root``` other than ```--source-mode```, they will be added to ```BOB_EMERGE_OPT='--color=y ...'```.

This is a bit more convenient when one is reviewing how all the packages will be installed in the ```/emerge-root/``` context for refinement and fine tuning.  I've been using the ```-t``` option to figure out what is pulling in a dependency and determine if its truly required.  If not, I mess with use flags to punt it.

If interested, is there any other function I should be calling in addition to ```configure_rootfs_build```?

**Comment by edannenberg** [comment]
I like the general idea but there seem to be a few misconceptions.

`kubler-build-root` is [build-root.sh](https://github.com/edannenberg/kubler/blob/master/engine/docker/bob-core/build-root.sh) renamed for clarity in the build container. It is the same script that is executed during the actual build to produce the `rootfs.tar`, so it already calls all the hooks like `configure_rootfs_build` in the proper order. Due to that executing `kubler-build-root` more then once per interactive build container is not recommended.

If I understood your use case correctly we could add a little helper function like `preview_packages` to `build-root.sh` that calls emerge on the `_packages` var with `-pt`. If it makes sense we could also add stuff to `BOB_EMERGE_DEFAULT_OPTS`.

> is there any other function I should be calling in addition to configure_rootfs_build?

Use flags set in the `configure_builder` hook will also affect `_packages`, however as there often are manual emerge calls in that hook it's probably not a good idea to call it every time. Probably best if `preview_packages` does not call any of the hooks, we could add a copy&paste snippet to the container startup message instead or maybe even another helper `preview_packages_with_hooks`.

**Comment by TerraTech** [comment]
Yeah - I should not have mentioned ```configure_rootfs_build```. I had just been running it to make quick checks in the builder and not the rootfs context.  It was a muscle-memory thing.

I like the idea of having little sub-command helpers in ```kubler-build-root```, and trying to make them multi run safe as we tweak the USE flags and such and rerun to check the new emerge portfolio.

I would surmise to achieve that would be to have two functions with the 2nd executed in a subshell.

_Simplified flow_
```sh
function _preview_packages() {
  set -u
  ['main procedural that will setup the context environment and run emerge "$@"']
}
export -f _preview_packages

function preview_packages() {
  local -a opts=('--color=y' '-pv')
  (( $# )) && opts=("$@")

  ['export any required envariables']
  bash -c _preview_packages "${opts[@]}"
}
```
That way after ```preview_packages``` is called, the environment is ephemeral and tossed.  Would that be enough to allow for this subcommand to be multiple call safe?  We'd also have to ensure that all the necessary envariables are properly exported to the subshell which I'd say could be hunted down with a ```set -u```.

I'd still like to have the ability to pass in specific ```emerge``` options, as there are times I'd like to see the ```-t``` output, and other times not.  I would say the minimum default options for ```preview_packages``` would be ```--color=y -pv```.

**Comment by edannenberg** [comment]
> That way after preview_packages is called, the environment is ephemeral and tossed. Would that be enough to allow for this subcommand to be multiple call safe?

It's a nice idea, but probably not needed as everything in the script should be in functions and with local vars. The tricky part are the file system changes that may happen during execution of a hook, `ROOT=/foo emerge <package-with-lots-of-deps>`, for example, will have different output on the second run. Or if a hook creates a new system user, the hook will fail on the next execution, etc. It's probably not feasable trying to deal with this compared to `ctrl-d & restart container`.

As I said earlier I like and support the general idea, but the more I think about it, it maybe not be worth the effort compared to the benefit. Maybe adding another section to the docs that goes into detail for a good daily workflow would be more worthwhile? 

That being said, feel free to play around until you find something that suits your workflow, I'm always open for improvements. Personally I rarely execute `kubler-build-root`, usually only to debug weird build issues where you want to check portage logs, etc. A couple manual `eix/emerge` calls in the builder usually does the trick figuring out deps and what to cut. (Thanks for the `-t` tip btw. :)

**Comment by TerraTech** [comment]
Fair enough.  I'd say this idea can be put on the backburner for a major release where this area can be refactored.
