### ISSUE TITLE
Building images for alternative architechtures

### ISSUE THREAD

**Issue by r7l** [edannenberg/kubler#200]
From what it looks like, i might be faced with the situation of people wanting to run my Kubler made images on newer Apple M1 chips in a not so distant future. This would require me to build for arm64 architecture next to amd64.

I am currently wondering how to accomplish that. So far i've come up with 3 possible options:

- it might be possible to use some ARM board like RPI 4 (which will probably take ages)
- use QEMU and build an arm64 based build system
- cross comiling with Kubler (which is probaly not supported as of yet)

Support in Kubler would be awesome but i guess, it would take allot of work. You ever thought about this?

**Comment by r7l** [comment]
Just a quick update: I was looking into cross compiling (never did before) and ruled that option out quick. It's actually pretty complicated on it's own and combined with Kubler + Docker i am not even sure if it would be possible for a number of reasons. One would be that Kubler couldn't execute the container while building it.

QEMU is also pretty much out of the question for me. I've set up a VM but emulating ARM is still quite slow on my PC.

So i am going to use a real ARM CPU for the task and most likely merge the images in the manifest files as explained [here](https://dev.to/toolboc/publish-multi-arch-docker-images-to-a-single-repo-with-docker-manifests-329n). Not there yet but given the flexibilty of Kubler and Gentoo, there shouldn't be to many issues.

Not sure if the issue is still needed and might close it once i am done and haven't encountered any problems along the path.

**Comment by berney** [comment]
Docker has qemu support built-in, when building images (works well with `docker buildx`) and with running images. I haven't tried it with kubler but in theory it should be possible on an amd64 machine to spin up kubler arm64 build container and "natively" compile arm64 software rather than trying to cross compile. Under the hood docker will be using qemu.

See https://docs.docker.com/desktop/multi-arch/.

Under the hood it uses https://github.com/tonistiigi/binfmt.

For me to build multi-arch images (in general, outside of kubler) for amd64 and arm64 I had to create a buildx builder. By default buildx will use the docker builder which is the original builder (e.g. the same one as `docker build`) that doesn't support multi-arch images. By creating a new builder (`docker buildx create`), then you can build for other archs. You will probably need to install the qemu binaries via tonistiigi/binfmt.

###  This is me running an ARM64 image on my AMD64 host.

First method by targeting platform specific image

```
docker run --rm arm64v8/alpine uname -m
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
aarch64
```

Second method by specifying platform

```
docker run --rm --platform arm64 alpine uname -m
Unable to find image 'alpine:latest' locally
latest: Pulling from library/alpine
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Downloaded newer image for alpine:latest
aarch64
```

The docker registry on localhost can only have one arch of an image at a time hence why it does a pull to change arch.

**Comment by r7l** [comment]
Thanks for your thoughts on this issue. While i am successfully building packages for AMD64 and ARM64 with Kubler, i haven't had the time or need to move on with it. It turned out that we are not going to buy Apple M1 machines as it was planned and for that reason, i am not in such a hurry as i was before and this issue is on hold from my part.

I am currently using an Odroid N2+ for the task. It's a much cleaner and better option when running Kubler. I don't want to move on using `buildx` as i want to stick as close to Kubler as possible. Main reason is that i only need to maintain the Kubler images and be able to stick to Gentoo and Portage by doing so.

Even if you said it's not possible to host multiple architectures for a single image, it does suggest otherwise in the article i've linked in the other comment. I still hope it actually works and i am still planning to test later on.

I could probably close the issue, since building images for ARM64 (and probably any other architecture) works perfectly well with Kubler. Merging or hosting images in a registry isn't something Kubler does care about nor should it.
